server:
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sleeve-api?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
#  打印 SQL
#  jpa:
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true

sleeve:
  security:
    jwt-key: sleeve
    token-expired-at: 86400000  # 1天